name: Assign Helm Name

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      helm_name: 'loads'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Helm Name
        id: set_helm_name
        run: |
          if [[ "${{ github.event.inputs.helm_name }}" == "load" ]]; then
            echo "load_svc" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.helm_name }}" == "layout" ]]; then
            echo "layout_svc" >> $GITHUB_ENV
          else
            echo "Invalid input. No helm_name will be set."
            exit 1
          fi

      - name: Display Helm Name
        run: echo "Helm Name:${{ env.helm_name }}"
