name: Assign Helm Name

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      helm_name: 'loads'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Helm Name
        id: set_helm_name
        run: |
          if [[ "${{ env.helm_name }}"  == "loads" || "${{ env.helm_name }}"  == "geography" ]]; then
             echo "helm_name=${{ env.helm_name }}_svc" >> $GITHUB_ENV
          elif [[ "${{ env.helm_name }}" == "layout" ]]; then
             echo "helm_name=${{ env.helm_name }}_svc" >> $GITHUB_ENV
          fi
      - name: Display Helm Name
        run: echo "Helm Name:${{ env.helm_name }} "
