name: Assign Helm Name

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      helm_name: 'loads'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Helm Name
        id: set_helm_name
        run: |
          if [[ $helm_name  == "loads" || $helm_name  == "geography" ]]; then
              $helm_name = loads_svc
          elif [[ "${{ env.helm_name }}" == "layout" ]]; then
              $helm_name = layout_svc
          fi

      - name: Display Helm Name
        run: echo "Helm Name:$helm_name "
